

# Localhost API CALL

POST http://localhost:3000
content-type: application/json

{
    "itemId":2,
    "itemName":"Python"
}

PATCH https://wy75n7lbha.execute-api.us-east-1.amazonaws.com/1
content-type: application/json

{
    "itemName":"Book"
}

GET http://localhost:3000/2

GET http://localhost:3000

DELETE http://localhost:3000/1

